[tool.black]
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | src/venv
)/
'''

[tool.ruff]
line-length = 120
exclude = ["venv", "src/venv"]

[tool.ruff.lint]
extend-select = ["I", "E", "F", "W"]
ignore = []

[tool.mypy]
python_version = 3.11
ignore_missing_imports = true
disallow_untyped_defs = false
check_untyped_defs = false

[tool.isort]
profile = "black"
skip = ["venv", "src/venv"]
